defmodule Helpdesk.Repo.TenantMigrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    tenants =
      if prefix() do
        [prefix()]
      else
        repo().all_tenants()
      end

    for prefix <- tenants do
      alter table(:users, prefix: prefix) do
        modify :id, :binary_id, null: false
      end
    end
  end

  def down do
    tenants =
      if prefix() do
        [prefix()]
      else
        repo().all_tenants()
      end

    for prefix <- tenants do
      alter table(:users, prefix: prefix) do
        modify :id, :binary_id, null: true
      end
    end
  end
end