defmodule Helpdesk.Repo.TenantMigrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    tenants =
      if prefix() do
        [prefix()]
      else
        repo().all_tenants()
      end

    for prefix <- tenants do
      create table(:users, primary_key: false, prefix: prefix) do
        add :id, :binary_id, primary_key: true
        add :representative, :boolean
        add :last_name, :text
        add :first_name, :text
      end
    end
  end

  def down do
    tenants =
      if prefix() do
        [prefix()]
      else
        repo().all_tenants()
      end

    for prefix <- tenants do
      drop table("users", prefix: prefix)
    end
  end
end